### PR TITLE
Update mpc.md

### PR DESCRIPTION
**Pull request by HuifengShrimp**
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

>  I have added a series of papers on Function Secret Sharing (FSS) to the MPC Series. FSS is a kind of MPC technique that allows parties to jointly compute a function on their private inputs without revealing any information about the inputs themselves. Compared to traditional secret-sharing techniques, FSS shares functions instead of values, which results in a faster online phase and reduces interactive communication.
>- [GI14] They proposed the distributed point function primitives, the earlier technique of function secret sharing.
>- [BGI15] This paper first described the function secret sharing formally.
>- [BGI16, BGI19, BCGI+21, BCGK22] These papers further proposed the distributed comparison function and the optimization.

### CODE REVIEW

**Comment by HuifengShrimp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by anakinxc** [comment]
Hi @HuifengShrimp 

Can you follow the steps in pr template and use the proper template for PETs?

Thanks

**Comment by HuifengShrimp** [comment]
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

>  I have added a series of papers on Function Secret Sharing (FSS) to the MPC Series. FSS is a kind of MPC technique that allows parties to jointly compute a function on their private inputs without revealing any information about the inputs themselves. Compared to traditional secret-sharing techniques, FSS shares functions instead of values, which results in a faster online phase and reduces interactive communication.
>- [GI14] They proposed the distributed point function primitives, the earlier technique of function secret sharing.
>- [BGI15] This paper first described the function secret sharing formally.
>- [BGI16, BGI19, BCGI+21, BCGK22] These papers further proposed the distributed comparison function and the optimization.

**Review by Jamie-Cui — APPROVED** [review]
LGTM

**Comment by Jamie-Cui** [comment]
Thanks for your contribution, you may add your github id to the contributors here: https://github.com/secretflow/secretflow/blob/main/docs/awesome-pets/awesome-pets.md

**Comment by llCurious** [comment]
Hey @HuifengShrimp . There are some recent FSS works that you miss like "Function Secret Sharing: Improvements and Extensions". Could you bother to check whether there are other missing works and supplement them?

**Pull request closed without merging**
