### PR TITLE
【OSCP】拆分学习梯度替换攻击、重放攻击和混淆自编码机的攻击算法实现(#770)

### PR DESCRIPTION
**Pull request by ZeroWalker10**
# Preamble

For Pull Request initiator, please read the following steps carefully. 请合并请求的发起人仔细阅读下列步骤。

---

If you are creating a `Pull Request` about listed topic below, please go the the `Preview` tab and click the relative link:
如果您要创建一个有关下列内容的的合并请求，请切换到 `Preview` 面板并点击下方相关的链接:

* Select [Awesome-PETs](?expand=1&template=pull_request_template_pets.md) for files under docs/awesome-pets

---

Select a proper `Pull Request` template can accelarate the review process, thanks for your cooperation.
选择一个正确的`合并请求`模版可以加速审查流程，谢谢您的配合

If your `Pull Request` topic is not amoung the list above, please just delete all prepopulated template content.
如果您的`合并请求`内容不在上述的列表里，请删除提前填入的模版内容。

---

Thanks for your contribution to SecretFlow project
感谢您对于 SecretFlow 项目的贡献

I have read the CLA Document and I hereby sign the CLA
Fix#770

### CODE REVIEW

**Review by ligw1998 — CHANGES_REQUESTED** [review]
I've sucessfully ran the experiment on the claimed secretflow version 0.8.3b. However, some changes have been made in secretflow version 1.2.0(the latest stable version). Is ist convenient for you to run the code on the latest secretflow version(1.2.0) and substitute the custome_base dir with the latest implementation? Thanks a lot.

**Comment by ZeroWalker10** [comment]
> I've sucessfully ran the experiment on the claimed secretflow version 0.8.3b. However, some changes have been made in secretflow version 1.2.0(the latest stable version). Is ist convenient for you to run the code on the latest secretflow version(1.2.0) and substitute the custome_base dir with the latest implementation? Thanks a lot.

Yeap. I have updated the implementations under directory `custom_base` and the examples can be run under secretflow:1.2.0 new. Please enjoy.

**Review by ligw1998 — CHANGES_REQUESTED** [review]
Can you make some minor changes as below:
1. In README, can you add a line to notify the user to change the default directory ('<local dataset path>') of dataset in the /dataset/dataset_config.py.
2. Can you make an empty dir named logs in the project dir to avoid confusion.

**Review by ligw1998 — APPROVED** [review]
All requirements met.

**Pull request merged**
