### PR TITLE
2 Comment errors

### PR DESCRIPTION
**Pull request by tarantula-leo**

### CODE REVIEW

**Comment by tarantula-leo** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **chengyuxiang5** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by tarantula-leo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by zhouaihui — APPROVED** [review]
LGTM

**Comment by zhouaihui** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **chengyuxiang5** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

@tarantula-leo 看起来你提交使用的邮箱和github账户没有绑定？

**Comment by tarantula-leo** [comment]
> > **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> > _**I have read the CLA Document and I hereby sign the CLA**_
> > **chengyuxiang5** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request
> 
> @tarantula-leo 看起来你提交使用的邮箱和github账户没有绑定？

提交的时候用的其它邮箱，刚刚绑定过了。

**Comment by 6fj** [comment]
> > > **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> > > _**I have read the CLA Document and I hereby sign the CLA**_
> > > **chengyuxiang5** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request
> > 
> > 
> > @tarantula-leo 看起来你提交使用的邮箱和github账户没有绑定？
> 
> 提交的时候用的内部邮箱账号，这个会有什么影响么？

这样是不行的，commit里面的邮箱需要和github邮箱保持一致。

**Comment by zhouaihui** [comment]
参见上面的说明，你的邮箱需要和你的账号绑定。
`
If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting recheck in this Pull Request
`

**Comment by 6fj** [comment]
recheck

**Pull request merged**
