### PR TITLE
Update he.md

### PR DESCRIPTION
**Pull request by wangsiyangwsy**
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> some papers about FHE-based MPC

### CODE REVIEW

**Comment by Jamie-Cui** [comment]
Hey @wangsiyangwsy thanks for your contribution, we have just updated the HE paper list, would be appreciated if you can fix the merge conflicts. :P

**Comment by xfap** [comment]
@wangsiyangwsy Hello, firstly, please modifiy the paper form to abide a consisitent style.
```markdown
- *Vadim Lyubashevsky Chris Peikert Oded Regev,*  
  [On Ideal Lattices and Learning with Errors Over Rings](https://eprint.iacr.org/2012/230.pdf)  
  Eurocrypt 2010

**should be**

- On Ideal Lattices and Learning with Errors Over Rings
  *Vadim Lyubashevsky, Chris Peikert, Oded Regev*  
  Eurocrypt 2010, [paper](https://eprint.iacr.org/2012/230.pdf), LPO10
```

Secondly, the paper like `Pyfhel: PYthon For Homomorphic Encryption Libraries` etcs, we better put it under `## Impl. Efforts`. Please put the alike papers to `## Impl. Efforts`.

Thirdly, the `### FHE-based MPC`  is a too general name and is a catagory like FHE's application, including too many aspects. We already have `### Multi-key FHE`

Besides, some papers already in our list. Please remove these. i.e. `*Kim Laine,*  [Simple Encrypted Arithmetic Library 2.3.1](https://www.microsoft.com/en-us/research/uploads/prod/2017/11/sealmanual-2-3-1.pdf)` is already in `## Impl. Efforts`

Thanks!

**Comment by xfap** [comment]
@wangsiyangwsy Hello, firstly, please modify the paper form to follow a consistent style.
```markdown
- *Vadim Lyubashevsky Chris Peikert Oded Regev,*  
  [On Ideal Lattices and Learning with Errors Over Rings](https://eprint.iacr.org/2012/230.pdf)  
  Eurocrypt 2010

**should be**

- On Ideal Lattices and Learning with Errors Over Rings
  *Vadim Lyubashevsky, Chris Peikert, Oded Regev*  
  Eurocrypt 2010, [paper](https://eprint.iacr.org/2012/230.pdf), LPO10
```

Secondly, the paper like `Pyfhel: PYthon For Homomorphic Encryption Libraries` etcs, we better put it under `## Impl. Efforts`. Please put the alike papers to `## Impl. Efforts`.

Thirdly, the `### FHE-based MPC`  is a too general name and is a catagory like FHE's application, including too many aspects. We already have `### Multi-key FHE` and we think these paper could be just named as a unified `### Multi-key & Threshold FHE` under `##FHE`.

Besides, some papers already in our list. Please remove these. i.e. `*Kim Laine,*  [Simple Encrypted Arithmetic Library 2.3.1](https://www.microsoft.com/en-us/research/uploads/prod/2017/11/sealmanual-2-3-1.pdf)` is already in `## Impl. Efforts`

Thanks!

**Comment by xfap** [comment]
@wangsiyangwsy Hi, cause long-time couldn't receive your reply, we have to close this PR after 24 hours. If you have time for this PR, we welcome you could update it at our request or create a new PR.

**Comment by liang-xiaojian** [comment]
Hi, @wangsiyangwsy, it would be appreciated to recheck the papers you added and fix the conflicts.
1. you may need to follow the existing format
```
- Title
- authors
- Conference, [eprint](https://github.com/secretflow/secretflow/pull/link), alias_name
```
2. some papers have already in he list, such as `"On-the-Fly Multiparty Computation on the Cloud via Multikey Fully Homomorphic Encryption"`,`"(Leveled) fully homomorphic encryption without bootstrapping"`, etc. Please recheck them and remove the repeating items.
3. remove the papers which have not been accepted by conference or journal. For example,  the paper `Faster Non-interactive Verifiable Computing`, which published in IACR, have withdrawn.
4. some papers you added in `Multi-key FHE` seems irrelevant to MK-FHE, such as,`Round-Optimal Secure Multi-party Computation`,`Single Secret Leader Election`, etc. Please recheck, thanks.

**Comment by xfap** [comment]
@wangsiyangwsy Hi, cause long-time couldn't receive your reply, we would close this PR after 24 hours. If you have time for this PR, we welcome you to update it according to our request or create a new PR after. Thanks for your contribution effort!

**Comment by sigmasdu** [comment]
Is there anything else that needs to be revised?

**Comment by wangsiyangwsy** [comment]
Is there anything else that needs to be revised?

**Pull request closed without merging**
