### PR TITLE
update he.md

### PR DESCRIPTION
**Pull request by palettis**
Type of change

- [x]  Add new papers (Please tell us why you think this paper is awesome!)
- [ ]  Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ]  Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

Description

> Added papers related to fully homomorphic encryption schemes, as well as papers on using hardware-accelerated fully homomorphic, and open source libraries for FHE,  which are important for how to use FHE.

### CODE REVIEW

**Comment by palettis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by palettis** [comment]
Type of change

- [x]  Add new papers (Please tell us why you think this paper is awesome!)
- [ ]  Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ]  Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

Description

> Added papers related to fully homomorphic encryption schemes, as well as papers on using hardware-accelerated fully homomorphic, and open source libraries for FHE,  which are important for how to use FHE.

**Comment by Jamie-Cui** [comment]
@liang-xiaojian @xfap Do you guys mind take another look at this PR?

**Comment by xfap** [comment]
@palettis Hello, thanks for your contributions. We've adopt a classifying method for HE paper(see [he.md](https://github.com/secretflow/secretflow/blob/main/docs/awesome-pets/papers/tools/he.md)), may you merge this change and add your papers in this PR to new suitable locations? Thanks!

**Pull request closed without merging**
