### PR TITLE
feat: Update psi.md

### PR DESCRIPTION
**Pull request by airmelt**
**Type of change**

- [X] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation. 
Their study the problem of private set-intersection in the multi-party setting and design two protocols with the following improvements compared to prior work. First, Their protocols are designed in the so-called star network topology, where a designated party communicates with everyone else, and take a new approach of leveraging the 2PC protocol. This approach minimizes the usage of a broadcast channel, where our semi-honest protocol does not make any use of such a channel and all communication is via point-to-point channels.In addition, the communication complexity of our protocols scales with the number of parties.

### CODE REVIEW

**Comment by airmelt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jamie-Cui** [comment]
LGTM, b.t.w, can you add two additional spaces at the end of the first two line?

Code:
```
- Scalable multi-party private set-intersection  
  *Carmit Hazay, Muthuramakrishnan Venkitasubramaniam*  
  PKC 2017, [eprint](https://eprint.iacr.org/2017/027)
```

p.s. You may also add you your name to the contributor list

**Comment by airmelt** [comment]
> 

sure, thanks for your quick review!

**Review by Jamie-Cui — APPROVED** [review]
LGTM

**Review by Jamie-Cui — APPROVED** [review]
LGTM

**Pull request merged**
