### PR TITLE
Update ZKP.md

### PR DESCRIPTION
**Pull request by Jinstorm**
**Type of change**

- [ ] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation.

Updated, but the content was motified too, should it be correct?

I also forget to add id in here too.
image

### CODE REVIEW

**Comment by xfap** [comment]
LTGM

**Review by xfap — APPROVED** [review]
LGTM

**Review by xfap — APPROVED** [review]
LGTM

**Review by Jamie-Cui — APPROVED** [review]
LGTM

**Pull request merged**
