### PR TITLE
Update zkp.md

### PR DESCRIPTION
**Pull request by zlyber**
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [x] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

    在General purpose ZKP下添加了两个子分支，ZKSNARKS和STARKS，目前general ZKP领域内主要的工作都集中在这两部分，许多ZKP社区也都以这种方式划分内容，如Ingonmaya；
    在分支内添加了各自的代表性文章，SNARKS中有部分论文与前文重复，但考虑到分支的完整性还是添加了。

### CODE REVIEW

**Comment by zlyber** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by xfap** [comment]
Hello, actually, here we just use a different category name.
- ZKSNARKS is contained in with `General purpose ZKP -> SRS(Structured Reference String)`
- For STARKS = Succinct (Scalable) Transparent ARguments of Knowledge, which is STARKs are SNARKs without Trusted Setup. SO it's actually contained in `General purpose ZKP - with URS(Uniform Reference String)`
image

So, if you think `ZKSNARKS & STARKS` category names matter, may you consider this approach by modifying existing name as:
```markdown
### with SRS(Structured Reference String), including ZKSNARK
...

### with URS(Uniform Reference String), including ZKSTARK
...
```

Then, add your paper below them in a appropriate location.
Thanks!

**Comment by zlyber** [comment]
I have adjusted the directory according to your requirements, added two classic articles of the SNARK scheme under the SRS branch, and added the recursive SNARK scheme **HALO** that does not require *setup* and a STARK articles **DEEP-FRI** under the URS branch

**Comment by Jamie-Cui** [comment]
@xfap Do you mind take another look at this PR?

**Review by xfap — APPROVED** [review]
lgtm

**Comment by xfap** [comment]
@zlyber Hello, thanks for you contribution! you may also add your github id to the contributors here:
https://github.com/secretflow/secretflow/blob/main/docs/awesome-pets/awesome-pets.md?plain=1#L14

**Pull request merged**
