### PR TITLE
Fix torch SL bug on model training and evaluation

### PR DESCRIPTION
**Pull request by Rorschach1989**
## Changes made:
- Fix training dataset evaluation & validation dataset evaluation bug when the scoring function returns tensors of shape [batch_size, 1], which are crucial in binary prediction tasks with metrics like AUROC
- Change the default behavior of parameter ``audit_log_dir`` in ``SLModel.fit``, since by default loading from intermediate checkpoints may encounter unintended behaviors.

### CODE REVIEW

**Comment by Rorschach1989** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by zhangxingmeng — DISMISSED** [review]
LGTM

**Review by zhouaihui — APPROVED** [review]
LGTM

**Comment by zhouaihui** [comment]
HI, @Rorschach1989, please rebase main branch to fix CI failure.

**Pull request merged**
