### PR TITLE
add more malicious security and zkp-based protocol

### PR DESCRIPTION
**Pull request by DuanYuFi**
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> In this PR, I tried to add more malicious security and zkp-based protocols in MPC.

## Preprocessing
In offline techniques, I tried to add a new H3 title named "preprocessing", which includes several preprocessing techniques. For example, daBit (double authenticated Bit), EdaBit (Extended Dabit), beaver triple generation by using cut-and-choose. They correspond to three papers.
- MArBled Circuits: Mixing Arithmetic and Boolean Circuits with Active Security. This paper introduces a new technique called "daBit" which can be used in many functionalities, such as share conversion, comparison, etc.
- Improved primitives for MPC over mixed arithmetic-binary circuits. This paper improves edaBit and introduces "Extended" edaBit to make better performance.
- High-Throughput Secure Three-Party Computation for Malicious Adversaries and an Honest Majority. This paper shows a new idea that generating binary beaver triples by using cut-and-choose and sacrifice. The average communication cost for  generating per triple is $3B-2$ where $B$ is bucket size.

## Malicious Secret Sharing
I also added some famous malicious security protocols. They are:
- An Efficient Passive-to-Active Compiler for Honest-Majority MPC over Rings. Known as SpdzWise in Ring. 
- Fantastic Four: Honest-Majority Four-Party Secure Computation With Malicious Security. An famous 4-pc honest majority malicious security protocol.
- Fast Large-Scale Honest-Majority MPC for Malicious Adversaries. Known as SpdzWise in Field. This is a famous malicious security protocol by using the idea of SPDZ secret sharing. The communication cost is approximately equal to double cost in corresponding semi-honest protocol. And the idea of verification is easy to understand.
- SPD $\mathbb {Z}_{2^k}$ : Efficient MPC mod $2^k$ for Dishonest Majority. In SPU of SecretFlow, this protocol is under development. And now it has a beta version in SPU with malicious security in online phase.
- Optimized Honest-Majority MPC for Malicious Adversaries — Breaking the 1 Billion-Gate Per Second Barrier. In this paper, the authors made deeper optimization above FLNW17. This is probably the state-of-the-art 3PC honest-majority malicious security binary protocol without distributed zkp technique. The communication cost per AND gate is 7 bits.

## Zero-Knowledge Proof
According to the current topic of academic community, distributed zero-knowledge proof is more and more popular in malicious security MPC protocols. The traditional zero-knowledge proof techniques have undergone a decade of development, leading to the emergence of distributed zero-knowledge proof techniques. To the best of my knowledge, the communication cost could be reduced into sublinear input size in multiplication protocols that achieves active security. So, I want to put some pioneer papers in this section.

- Zero-Knowledge Proofs on Secret-Shared Data via Fully Linear PCPs. This is the first paper that applied dzkp into MPC protocols.
- Practical Fully Secure Three-Party Computation via Sublinear Distributed Zero-Knowledge Proofs. A communication cheap protocol that used dzkp. Works on both Field and Extension Ring.

### CODE REVIEW

**Comment by DuanYuFi** [comment]
Sorry, I didn't follow the PR example. I will update later in the comments.

**Comment by DuanYuFi** [comment]
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> In this PR, I tried to add more malicious security and zkp-based protocols in MPC.

## Preprocessing
In offline techniques, I tried to add a new H3 title named "preprocessing", which includes several preprocessing techniques. For example, daBit (double authenticated Bit), EdaBit (Extended Dabit), beaver triple generation by using cut-and-choose. They correspond to three papers.
- MArBled Circuits: Mixing Arithmetic and Boolean Circuits with Active Security. This paper introduces a new technique called "daBit" which can be used in many functionalities, such as share conversion, comparison, etc.
- Improved primitives for MPC over mixed arithmetic-binary circuits. This paper improves edaBit and introduces "Extended" edaBit to make better performance.
- High-Throughput Secure Three-Party Computation for Malicious Adversaries and an Honest Majority. This paper shows a new idea that generating binary beaver triples by using cut-and-choose and sacrifice. The average communication cost for  generating per triple is $3B-2$ where $B$ is bucket size.

## Malicious Secret Sharing
I also added some famous malicious security protocols. They are:
- An Efficient Passive-to-Active Compiler for Honest-Majority MPC over Rings. Known as SpdzWise in Ring. 
- Fantastic Four: Honest-Majority Four-Party Secure Computation With Malicious Security. An famous 4-pc honest majority malicious security protocol.
- Fast Large-Scale Honest-Majority MPC for Malicious Adversaries. Known as SpdzWise in Field. This is a famous malicious security protocol by using the idea of SPDZ secret sharing. The communication cost is approximately equal to double cost in corresponding semi-honest protocol. And the idea of verification is easy to understand.
- SPD $\mathbb {Z}_{2^k}$ : Efficient MPC mod $2^k$ for Dishonest Majority. In SPU of SecretFlow, this protocol is under development. And now it has a beta version in SPU with malicious security in online phase.
- Optimized Honest-Majority MPC for Malicious Adversaries — Breaking the 1 Billion-Gate Per Second Barrier. In this paper, the authors made deeper optimization above FLNW17. This is probably the state-of-the-art 3PC honest-majority malicious security binary protocol without distributed zkp technique. The communication cost per AND gate is 7 bits.

## Zero-Knowledge Proof
According to the current topic of academic community, distributed zero-knowledge proof is more and more popular in malicious security MPC protocols. The traditional zero-knowledge proof techniques have undergone a decade of development, leading to the emergence of distributed zero-knowledge proof techniques. To the best of my knowledge, the communication cost could be reduced into sublinear input size in multiplication protocols that achieves active security. So, I want to put some pioneer papers in this section.

- Zero-Knowledge Proofs on Secret-Shared Data via Fully Linear PCPs. This is the first paper that applied dzkp into MPC protocols.
- Practical Fully Secure Three-Party Computation via Sublinear Distributed Zero-Knowledge Proofs. A communication cheap protocol that used dzkp. Works on both Field and Extension Ring.

**Comment by Jamie-Cui** [comment]
Thanks for the contribution, you can also add you github id in the contributor list, which is in https://github.com/secretflow/secretflow/blob/main/docs/awesome-pets/awesome-pets.md

**Comment by DuanYuFi** [comment]
> Thanks for the contribution, you can also add you github id to our contributor list, which is in https://github.com/secretflow/secretflow/blob/main/docs/awesome-pets/awesome-pets.md

What a great honor :)

**Comment by anakinxc** [comment]
Hi @DuanYuFi 

I just moved your templated based content to top. Please double check :D

**Comment by DuanYuFi** [comment]
> Hi @DuanYuFi
> 
> I just moved your templated based content to top. Please double check :D

Looks great. Thank you :)

**Comment by xfap** [comment]
Hello! 
Paper(Zero-Knowledge twenty years after its invention) may belongs to the kind as `survey`, so may you add a new H2 title as `## Survey & Tutorial` and add it after the title.
image

FYI, here is a newer version [paper](https://www.wisdom.weizmann.ac.il/~oded/PSX/zk-tut10.pdf) from [Zero-Knowledge: a tutorial by Oded Goldreich](https://www.wisdom.weizmann.ac.il/~oded/zk-tut02.html)

In short, suggest add the paper as
```markdown
...
## Survey & Tutorial
- Zero-Knowledge twenty years after its invention, also called A Short Tutorial of Zero-Knowledge
  *Oded Goldreich*  
  Gol10, [paper](https://www.wisdom.weizmann.ac.il/~oded/PSX/zk-tut10.pdf), [Gol04 older version](https://www.wisdom.weizmann.ac.il/~oded/PSX/zk-tut02v4.pdf),[homepage](https://www.wisdom.weizmann.ac.il/~oded/zk-tut02.html)

## Milestones
...
```
Thanks~

**Comment by DuanYuFi** [comment]
> @DuanYuFi Hello! Paper(Zero-Knowledge twenty years after its invention) may belongs to the kind as `survey`, so may you add a new H2 title as `## Survey & Tutorial` and add it after the title. image
> 
> FYI, here is a newer version [paper](https://www.wisdom.weizmann.ac.il/~oded/PSX/zk-tut10.pdf) from [Zero-Knowledge: a tutorial by Oded Goldreich](https://www.wisdom.weizmann.ac.il/~oded/zk-tut02.html)
> 
> In short, suggest add the paper as
> 
> ```gfm
> ...
> ## Survey & Tutorial
> - Zero-Knowledge twenty years after its invention, also called A Short Tutorial of Zero-Knowledge
>   *Oded Goldreich*  
>   Gol10, [paper](https://www.wisdom.weizmann.ac.il/~oded/PSX/zk-tut10.pdf), [Gol04 older version](https://www.wisdom.weizmann.ac.il/~oded/PSX/zk-tut02v4.pdf),[homepage](https://www.wisdom.weizmann.ac.il/~oded/zk-tut02.html)
> 
> ## Milestones
> ...
> ```
> 
> Thanks~

Thank you for reminding. I have updated them. :)

**Review by xfap — APPROVED** [review]
lgtm

**Pull request merged**
