### PR TITLE
docs: update references on homomorphic encryption

### PR DESCRIPTION
**Pull request by zhangwfjh**
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [x] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

1. add a link to SOTA papers on FHE from Shai
2. add a hardware acceleration paper on HE
3. link to the dangling HE document at the main page

### CODE REVIEW

**Comment by xfap** [comment]
Hello, thanks for your contributions.
Please don't delete and reserve the files `fe.md` & `tpm.md`. 
And we suggest add a category named `## Other Resources` in the end of `he.md`, instead of placing at the beginning.
Then, the paper `Intel HEXL`'s form is not right
image
 Please format it as below:
```
- Intel HEXL: Accelerating Homomorphic Encryption with Intel AVX512-IFMA52  
  *Fabian Boemer, Sejun Kim, Gelila Seifu, Fillipe D. M. de Souza, Vinodh Gopal*  
  Proceedings of the 9th on Workshop on Encrypted Computing & Applied Homomorphic Cryptography 2021, [paper](https://dl.acm.org/doi/abs/10.1145/3474366.3486926), BKS+21
```

**Review by xfap — APPROVED** [review]
LGTM

**Review by xfap — APPROVED** [review]
LGTM

**Review by Jamie-Cui — APPROVED** [review]
LGTM

**Pull request merged**
