### PR TITLE
在secretflow中实现两个AIGC Security算法（RAG相关）

### PR DESCRIPTION
**Pull request by lcy5201314**
**Type of change**

本PR添加了RAG Security
1.PoisonedRAG: Knowledge Corruption Attacks to Retrieval-Augmented Generation of Large Language Models
2.Poisoning Retrieval Corpora by Injecting Adversarial Passages

### CODE REVIEW

**Comment by usafchn** [comment]
Interesting！

**Comment by usafchn** [comment]
@lcy5201314 感谢您的工作，Paper 和代码我都简单看了一下，一个主要的问题是 RAG 知识库投毒与 Secretflow 仓库的功能并不完全相关，然后这两 Paper 都有官方仓库，本 PR 与官方仓库的代码重复率较高，建议直接提给官方仓库更合适哈

**Comment by lcy5201314** [comment]
@usafchn 很高兴这部分内容可以得到您的关注，我是网络安全学院学生创新资助计划的学生之一，这部分关于RAG的调研和复现是我和蚂蚁开源社区合作交流的一部分，为此提交到隐语的aigc下面。如果后续有其他需求和改动，我很乐意配合和修改，此外，我也很关注隐私计算方向，同时也在做MPC相关的研究，希望未来有机会可以进一步的参与隐语，合作交流。

**Comment by lcy5201314** [comment]
@usafchn 没事，很感谢您的关注，虽然目前是复现别人的研究，也希望未来可以和隐语团队一起做出更好的研究内容。

**Comment by lcy5201314** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lcy5201314** [comment]
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> **lcy5201314** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

Recheck

**Comment by lcy5201314** [comment]
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/secretflow/.github/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> **lcy5201314** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

recheck
I have read the CLA Document and I hereby sign the CLA

**Comment by lcy5201314** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 6fj** [comment]
hi @lcy5201314 

看上去你没有正确配置git邮箱，导致CLA assistant无法正确识别，麻烦调整一下确保commit history可以被github识别。感谢！

**Comment by lcy5201314** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 6fj** [comment]
之前的commit 需要一并处理才行，不然cla还是通过不了

**Comment by lcy5201314** [comment]
@6fj 那我把这个提交删了，重新提交一次吧

**Comment by 6fj** [comment]
> @6fj 那我把这个提交删了，重新提交一次吧

可以的，感谢

**Pull request closed without merging**
