### PR TITLE
Update vertical.md

### PR DESCRIPTION
**Pull request by lidh15**
**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation. 

I'd like to introduce one of my works on vertical federated learning, which focused on Non-IID problem.
In many application domains, especially the financial domain we discussed in the paper, the data for binary classification are heavily imbalanced, which is an important cause of poor performance in vertical federated learning.
This paper utilized widely used cryptographic techniques and conducted FEDERATED data under-sampling in the PSI procedure,
the metrics of downstream modeling tasks showed that it is an effective approach for mediating the imbalance problem.

### CODE REVIEW

**Comment by lidh15** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lidh15** [comment]
recheck

**Review by zhangxingmeng — COMMENTED** [review]
Thanks for your recommendation, This paper cannot be accepted to the paper-list as it did not meet the minimum requirement for a Grade B conference

**Comment by lidh15** [comment]
well, okay

**Pull request closed without merging**
